<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZfDeals - Administration') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/zf-deals/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
</head>



<div class="container">

    <?php echo $this->content; ?>

</div> <!-- /container -->

<?php echo $this->inlineScript() ?>
</body>
</html>
